# This file was generated by the {rix} R package v0.18.1 on 2026-01-27
# with following call:
# >rix(date = "2026-01-19",
#  > r_pkgs = c("dplyr",
#  > "ggplot2",
#  > "reticulate",
#  > "yardstick",
#  > "testthat",
#  > "withr"),
#  > git_pkgs = list(list(package_name = "rix",
#  > repo_url = "https://github.com/ropensci/rix/",
#  > commit = "HEAD"),
#  > list(package_name = "rixpress",
#  > repo_url = "https://github.com/ropensci/rixpress",
#  > commit = "HEAD")),
#  > py_conf = list(py_version = "3.13",
#  > py_pkgs = c("numpy",
#  > "pandas",
#  > "scikit-learn",
#  > "matplotlib",
#  > "seaborn",
#  > "pytest"),
#  > git_pkgs = list(list(package_name = "ryxpress",
#  > repo_url = "https://github.com/b-rodrigues/ryxpress",
#  >      commit = "HEAD"))),
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > r_ver = "4.5.2")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2026-01-19.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      dplyr
      ggplot2
      reticulate
      testthat
      withr
      yardstick;
  };
 
    rix = (pkgs.rPackages.buildRPackage {
      name = "rix";
      src = pkgs.fetchgit {
        url = "https://github.com/ropensci/rix/";
        rev = "HEAD";
        sha256 = "sha256-k4WKNwW6dWnrPRp8ro+NmWJC//k9zvhL2MUu0xMDya0=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          codetools
          curl
          jsonlite
          sys;
      };
    });

    rixpress = (pkgs.rPackages.buildRPackage {
      name = "rixpress";
      src = pkgs.fetchgit {
        url = "https://github.com/ropensci/rixpress";
        rev = "HEAD";
        sha256 = "sha256-nHpkYX5860vaLB3PVmPTRAQ2/usITpFTsX2qwcjh79w=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          cli
          igraph
          jsonlite
          processx;
      };
    });
   

    ryxpress = (pkgs.python313Packages.buildPythonPackage {
      pname = "ryxpress";
      version = "HEAD-git";
      src = pkgs.fetchgit {
        url = "https://github.com/b-rodrigues/ryxpress";
        rev = "HEAD";
        sha256 = "sha256-KcRm8DI6KA1pTX5bgotZLoW9XXl+OdYxC5QqSfWKFqE=";
      };
      pyproject = true;
      build-system = [ pkgs.python313Packages.setuptools ];
      doCheck = false;
      propagatedBuildInputs = [ ];
    });
 
  pyconf = builtins.attrValues {
    inherit (pkgs.python313Packages) 
      pip
      ipykernel
      matplotlib
      numpy
      pandas
      pytest
      scikit-learn
      seaborn;
  } ++ [ ryxpress ];
   
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      python313
      R;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    RETICULATE_PYTHON = "${pkgs.python313}/bin/python";

    buildInputs = [ rix rixpress rpkgs pyconf system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
